# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AroundEgyptTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AroundEgyptTask
  pod 'Alamofire', '~> 5.10'
  pod 'SDWebImageSwiftUI'
  
  target 'AroundEgyptTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AroundEgyptTaskUITests' do
    # Pods for testing
  end

end
